<?php
/**
 * Cybage Marketplace Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Marketplace Plugin
 * @package    Cybage_Marketplace
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */
$_helper = $this->helper('catalog/output');
?>
<?php $_product = $this->getProduct(); ?>

<?php if ($_product->getSellerId()): ?>
    <section class="mproductView">
        <div class="mproductView__title bshead">
            
            <h2><?php echo $this->__('Sobre o vendedor') ?></h2>
        </div>
        <div class="mbox row mproductView__container">
            <?php $sellerId = $_product->getSellerId() ;
                $sellerName = $this->getSellerName($sellerId);
                $sellerData = Mage::helper('marketplace')->getSellerInfo($sellerName);
                // var_dump($sellerData);
                $sellerCompany = $this->getSellerCompany($sellerId);
            ?>
        <div class="cold-xs-12 col-md-2 company-banner">
            
            <img class="mproductView__logo" src="<?php echo $sellerData['company_logo']?>"  />
        </div>                          

            <div class="col-xs-12 col-md-7">
                        <?php
                        $sellerUrl = $this->getBaseUrl() . "marketplace/" . str_replace(' ', '-', $sellerCompany) . ".html";
                        ?>

                            <h2><?php echo $sellerCompany; ?></h2>
                            <a href="<?php echo $sellerUrl; ?>" title="<?php echo $sellerCompany; ?>" class="mlink--secundary">Ver todos os produtos do vendedor</a>
                                <?php echo $html; ?>

                        
            </div>

            <div class="col-xs-12 col-md-3">
                    <a class="ask-action"><img class="img-responsive" style="display:inline-block" src="http://i.imgur.com/7A9EUgY.png" /> Faça uma pergunta ao vendedor</a>
                <?php echo $this->getChildHtml('product_askquestion_link') ?>
            </div>
<script>
    jQuery(document).ready(function(){
        $ = jQuery;
        $('.ask-action').click(function(){
            $('#askquestion').click();
        });
    })
</script>
        </div>
    </section>
<?php endif;?>