<?php 
$_categories = Mage::getModel('catalog/category')->getCollection()
                        ->addAttributeToFilter('is_active', 1)
                        ->addAttributeToFilter('bottom_description', 1);


if (count($_categories) > 0){ ?>
    <div class="mcategoriesBadges">
    <div class="bshead">
            <h2><?php echo $this->__('Categories'); ?></h2>
    </div>
    <div class="mcategoriesBadges__itens">
        <?php
        
        foreach($_categories as $_category){

            $_category = Mage::getModel('catalog/category')->load($_category->getId()); ?>
            <div class="mcategoriesBadges__item">
                <a href="<?= $_category->getUrl(); ?>" class="mcategoriesBadges__title"><?= $_category->getName(); ?></a>
                <?php
                $_subcategories = $_category->getChildrenCategories();
                if (count($_subcategories) > 0){ ?>
                    <ul>
                    
                        
                <?php
                    foreach($_subcategories as $_subcategory){ ?>
                        <li class="mcategoriesBadges__itemlist">
                            <a href="<?= $_subcategory->getUrl(); ?>">
                                <span class="mcategoriesBadges__badge badge"><?= $_subcategory->getName(); ?></span>
                            </a>
                        </li>
                        <?php
                    } ?>
                    </ul>
                <?php } ?>
                </div>
        <?php } 
        ?>
        </div>
    </div>
<?php } ?>