
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products">Gerenciar Anúncios</h3></td>
        <td class="a-right">
            <?php //echo $this->getButtonsHtml() ?>
        </td>
    </tr>
</table>
</div>

<div>
	Não conectado, necessário conectar para ver os produtos.
    <?php //echo $this->getGridHtml() ?>
    <br />
    -> <?php echo $this->getChildHtml('anuncios_grid'); ?><br />
    -> <?php echo $this->getIsTeste(); ?><br />
</div>
